Traceback (most recent call last):
  File "/tmp/ipykernel_197/2142403542.py", line 4, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
